config/routes.rb
Rails.application.routes.draw do
  get "top/main"
  post "top/login"
  get "top/logout"
  
  resources :users
  resources :tweets
  resources :likes
  
  root 'tweets#index'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  # root "posts#index"
  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/like.rb
class Like < ApplicationRecord
    belongs_to :user
    belongs_to :tweet
end

app/models/tweet.rb
class Tweet < ApplicationRecord
    belongs_to :user
    has_many :likes, dependent: :destroy
    has_many :users, through: :likes , source: :user
    
    def like(user)
        likes.create(user_id: user.id)
    end
    
    def unlike(user)
        likes.find_by(user_id: user.id).destroy
    end
    
    def liked?(user) #いいね済みか調べる(true / false)
        users.include?(user)
    end
end

app/models/user.rb
class User < ApplicationRecord
    has_many :tweets, dependent: :destroy
    has_many :likes, dependent: :destroy
    has_many :like_tweets, through: :likes, source: :tweet
    has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Only allow modern browsers supporting webp images, web push, badges, import maps, CSS nesting, and CSS :has.
  allow_browser versions: :modern
  
  helper_method :current_user
  private
    def current_user
      if session[:login_uid]
        User.find_by(uid: session[:login_uid])
      end
    end
end

app/controllers/like_controller.rb
class LikeController < ApplicationController
  def user_id:integer
  end

  def tweet_id:integer
  end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  def create
    tweet = Tweet.find(params[:tweet_id])
    unless tweet.liked?(current_user)
      tweet.like(current_user)
    end
    redirect_to root_path
  end
  
  def destroy
    tweet = Tweet.find(params[:id])
    if tweet.liked?(current_user)
      tweet.unlike(current_user)
    end
    redirect_to root_path
  end
end

app/controllers/top_controller.rb
class TopController < ApplicationController
  def main
    render "login_form"
  end
  
  def login
    user = User.find_by(uid: params[:uid])
    if user and user.authenticate(params[:pass])
      session[:login_uid] = params[:uid]
      redirect_to tweets_path
    end  
  end
  
  def logout
    session.delete(:login_uid)
    redirect_to tweets_path
  end
end

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController
  def index
    @tweets = Tweet.all
  end

  def new
    @tweet = Tweet.new
  end

  def create
    tweet = Tweet.new(message: params[:tweet][:message],user_id: 5)
    tweet.save
    redirect_to tweets_path
  end

  def destroy
    tweet = Tweet.find(params[:id])
    tweet.destroy
    redirect_to tweets_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
  end

  def new
    @users = User.new
  end

  def create
    user = User.new(uid: params[:user][:uid],
                    password:params[:user][:password],
                    password_confirmation:params[:user][:password_confirmation])
    user.save
    redirect_to users_path
  end

  def destroy
    user = User.find(params[:id])
    user.destroy
    redirect_to users_path
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/like_helper.rb
module LikeHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/top_helper.rb
module TopHelper
end

app/helpers/tweets_helper.rb
module TweetsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "L5" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <%# Enable PWA manifest for installable apps (make sure to enable in config/routes.rb too!) %>
    <%#= tag.link rel: "manifest", href: pwa_manifest_path(format: :json) %>

    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">

    <%# Includes all stylesheet files in app/assets/stylesheets %>
    <%= stylesheet_link_tag :app, "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/like/tweet_id:integer.html.erb
<h1>Like#tweet_id:integer</h1>
<p>Find me in app/views/like/tweet_id:integer.html.erb</p>

app/views/like/user_id:integer.html.erb
<h1>Like#user_id:integer</h1>
<p>Find me in app/views/like/user_id:integer.html.erb</p>

app/views/top/login_form.html.erb
<%= form_with url: '/top/login', method: :post, local: true do |f| %>
    <%= f.label :uid, 'ユーザーID' %>
    <%= f.text_field :uid %>
    <%= f.label :pass, 'パスワード' %>
    <%= f.password_field :pass %>
    <%= f.submit 'ログイン' %>
<% end %>

app/views/top/main.html.erb
<h1>Top#main</h1>
<p>Find me in app/views/top/main.html.erb</p>

app/views/tweets/index.html.erb
<% @tweets.each do |u| %>
  <p>
      <%= u.message %>
      <%= u.users.count %>
      <%= link_to '削除', tweet_path(u), data: {turbo_method: :delete} %>
      
      <% if session[:login_uid] %>
        <%= link_to 'いいね', likes_path(tweet_id: u.id), data: { turbo_method: :post } %>
        <%= link_to 'いいね削除', like_path(u), data: { turbo_method: :delete } %>
      <% end %>
  </p>
<% end %>
<p>
      <%= link_to '新規追加', new_tweet_path %>
      <%= link_to 'ログイン',top_main_path %>
      <%= link_to 'ログアウト',top_logout_path %>
      ログイン中UID：<%= session[:login_uid] %>
</p>

app/views/tweets/new.html.erb
<%= form_with model: @tweet do |f| %>
  <%= f.label :message, 'つぶやき' %>
  <%= f.text_field :message %>
  <%= f.submit 'ツイート' %>
<% end %>

app/views/users/create.html.erb
<%= form_with model: @user do |f| %>
  <%= f.label :uid, 'ユーザーID' %>
  <%= f.text_field :uid %>
  <%= f.label :pass, 'パスワード' %>
  <%= f.text_field :pass %>
  <%= f.submit '更新' %>
<% end %>

app/views/users/destroy.html.erb
<h1>Users#destroy</h1>
<p>Find me in app/views/users/destroy.html.erb</p>

app/views/users/index.html.erb
<% @users.each do |u| %>
  <p>
      uid: <%= u.uid %>, 
      password_digest: <%=u.password_digest %>
      <%= link_to '削除', user_path(u), data: {turbo_method: :delete} %>
  </p>
<% end %>
<p><%= link_to '新規追加', new_user_path %></p>

app/views/users/new.html.erb
<%= form_with model: @users do |f| %>
  <%= f.label :uid, 'UID' %>
  <%= f.text_field :uid %>
  <%= f.label :password, 'PASS' %>
  <%= f.text_field :password %>
  <%= f.label :password_confirmation, 'パスワード(確認)' %>
  <%= f.text_field :password_confirmation %>
  <%= f.submit '登録' %>
<% end %>